Update the episcanner code to run the data in the Nov-Nov window
AlertaDengue/episcanner-downloader pull request #26
Opened 2024-04-29 13:53 UTC by eduardocorrearaujo

Changes done in utils.py: 
* minor changes in `obj_fun`;
* add pars to comp the int value of begin and end in relation to the 52 window in the `comp_duration`; 
* minor changes in `otim`; 

Changes in the `Episcanner` class: 
* Change the filter in `__init__` to allow the episcanner application in the current year and only above 2011 (since we don't have the data of '2009-11' to apply the model in 2010). 
* update `has_transmission` condition to use the p_rt1 and sum of cases as filter criteria. 
* add `t_ini` and `t_end` on the save_results

2024-04-29 16:25 UTC, luabida requested changes

2024-04-29 16:25 UTC, luabida commented on src/scanner/scanner.py
> +        # dfcity["casos_cum"] = dfcity.casos.cumsum()
any reason to keep this comment in the code? if it's not used anymore, it can be removed

2024-04-29 16:25 UTC, luabida commented on src/scanner/scanner.py
> +        # dfy = df[df.year == self.year]
same here

2024-04-29 16:25 UTC, luabida commented on src/scanner/scanner.py
> +        # dfy = df[df.year == self.year]
same here

2024-04-29 19:20 UTC, fccoelho approved these changes

2024-04-30 13:08 UTC, luabida approved these changes
LGTM

2024-04-30 13:25 UTC, merged